### ISSUE TITLE
self.__emitting AssertionError intemittenly

### ISSUE THREAD

**Issue by shikharvaish28** [NagarajuGunda/PyAlgoMate#29]
```
Traceback (most recent call last):
  File "/Users/shikhar.vaish/Downloads/pheonix_project/atlas/pyalgomate/brokers/zerodha/feed.py", line 218, in dispatch
    if super(ZerodhaLiveFeed, self).dispatch():
  File "/Users/shikhar.vaish/Downloads/pheonix_project/atlas/.atlas/lib/python3.9/site-packages/pyalgotrade/feed/__init__.py", line 108, in dispatch
    self.__event.emit(dateTime, values)
  File "/Users/shikhar.vaish/Downloads/pheonix_project/atlas/.atlas/lib/python3.9/site-packages/pyalgotrade/observer.py", line 69, in emit
    self.__applyChanges()
  File "/Users/shikhar.vaish/Downloads/pheonix_project/atlas/.atlas/lib/python3.9/site-packages/pyalgotrade/observer.py", line 44, in __applyChanges
    assert not self.__emitting
AssertionError
```

**Comment by shikharvaish28** [comment]
@AnveshMora by any chance are you facing this issue with Zerodha?

**Comment by AnveshMora** [comment]
I am not using the code anymore! But what is the issue you are facing?

**Comment by shikharvaish28** [comment]
@AnveshMora  I am not using the code as well now

**Comment by NagarajuGunda** [comment]
The feed has been brought out for finvasia and the broker module feed need to be updated to use zmq like it has been implemented for finvasia. Zerodha/Kotak are not yet updated
