### ISSUE TITLE
Flet: AssertionError: Control must be added to the page first.

### ISSUE THREAD

**Issue by shikharvaish28** [NagarajuGunda/PyAlgoMate#30]
```
Unhandled error processing page session : Traceback (most recent call last):
  File "/Users/shikhar.vaish/Downloads/pheonix_project/atlas/.atlas/lib/python3.9/site-packages/flet_runtime/app.py", line 242, in on_session_created
    await asyncio.get_running_loop().run_in_executor(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/tasks.py", line 328, in __wakeup
    future.result()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/shikhar.vaish/Downloads/pheonix_project/atlas/flet/PyAlgoMate.py", line 253, in main
    page.views[-1].update()
  File "/Users/shikhar.vaish/Downloads/pheonix_project/atlas/flet/views/trades.py", line 176, in update
    self.collectedPremiumText.update()
  File "/Users/shikhar.vaish/Downloads/pheonix_project/atlas/.atlas/lib/python3.9/site-packages/flet_core/control.py", line 293, in update
    assert self.__page, "Control must be added to the page first."
AssertionError: Control must be added to the page first.
```

<img width="803" alt="Screenshot 2024-05-02 at 12 11 06 PM" src="https://github.com/NagarajuGunda/PyAlgoMate/assets/22795943/c61af814-8dfe-4af2-8101-22bacb11e18f">

**Comment by NagarajuGunda** [comment]
This was coming as we are trying to update the top view every 0.5/1 second and we are recreating the view everytime instead of just updating the control data.

I have updated strategies.py to know if the control has been mounted and proceed with update only if mounted, I guess this fix should solve the problem
